environment:
  nodejs_version: 18.18.2

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm@latest -g
  - npm ci

test_script:
  - node --version
  - npm --version
  - npm test

build: false
