name: Generate Changelog

on:
  pull_request_target:
    types:
      - closed

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch git tags
        run: git fetch --unshallow --tags

      - name: Generate changelog
        run: bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/generate-local-changelog/main/bin/generate-local-changelog) --unreleased --include-incomplete-merges > CHANGELOG.md

      - name: Setup git
        run: |
          git config user.name "neogeek-bot"
          git config user.email "neogeek0101+bot@gmail.com"

      - name: Git commit changes
        run: |
          git pull
          git add CHANGELOG.md
          git commit -m "Updated CHANGELOG.md [skip ci]" || exit 0
          git push origin main
